#!/bin/bash
#SBATCH --job-name=hybrid_advection
#SBATCH --output=test.out
#SBATCH --nodes=4
#SBATCH --cpus-per-task=16
#SBATCH --partition=caslake

module load openmpi
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
mpirun ./test